name: Terraform

on:
  push:
    branches: ["develop", "main"]
  workflow_run:
    workflows: ["CI"]

env:
  AWS_REGION: us-east-1

jobs:
  development:
    runs-on: ubuntu-latest
    environment: develop
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      APP_NAME: ${{ vars.APP_NAME }}
    steps:
      - uses: actions/checkout@v4
        name: Git Checkout

      - uses: aws-actions/configure-aws-credentials@v4
        name: AWS Login
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - uses: hashicorp/setup-terraform@v3
        name: Terraform Setup

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var environment=${{ env.ENVIRONMENT }} -var app_name=${{ env.APP_NAME }}




