name: TerraformDev

on:
  push:
    branches: ["develop"]
  workflow_run:
    workflows: ["CI"]
    types: completed

env:
  AWS_REGION: us-east-1
  AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TF_STATE_PATH: terraform/terraform.tfstate
  TF_WORK_DIR: ./terraform

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    env:
      ENV: ${{ vars.ENVIRONMENT }}
      APP: ${{ vars.APP_NAME }}
      TF_STATE_BUCKET: ${{ vars.TF_STATE_S3_BUCKET }}
      TF_STATE_KEY: ${{ vars.TF_STATE_S3_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform init \
          -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ env.TF_STATE_KEY }}" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="encrypt=true"

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform plan -var environment=${{ env.ENV }} -var app_name=${{ env.APP }}



